{% set name = "elyra-scala-editor-extension" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f80e135fdb71290143796229c1edff31ddcf6d2615060aaf0cf9c0fca64bc095

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - jupyter_packaging
    - pip
  run:
    - python >={{ python_min }}
    - elyra-server =={{ version }}
    - jupyter_packaging

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra provides AI Centric extensions to JupyterLab
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
